name: Build RMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: rmk-rs/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
